create type "public"."SUPPORTED_COUNTRIES" as enum ('Norway', 'England', 'Sweden', 'Denmark', 'Finland', 'Germany');

create type "public"."SUPPORTED_LANGUAGES" as enum ('Norwegian', 'English', 'Swedish', 'Danish', 'Finnish', 'German');

create table "public"."BusinessAccount" (
    "id" uuid not null default gen_random_uuid(),
    "country" "SUPPORTED_COUNTRIES" not null,
    "org_number" character varying not null,
    "business_name" text not null,
    "person_fullname" text not null,
    "phonenumber" character varying not null,
    "email" character varying not null,
    "language" "SUPPORTED_LANGUAGES" not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."BusinessAccount" enable row level security;

create table "public"."CountryVAT" (
    "id" bigint generated by default as identity not null,
    "country" "SUPPORTED_COUNTRIES" not null,
    "vat" double precision not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."CountryVAT" enable row level security;

CREATE UNIQUE INDEX "BusinessAccount_email_key" ON public."BusinessAccount" USING btree (email);

CREATE UNIQUE INDEX "BusinessAccount_org_number_key" ON public."BusinessAccount" USING btree (org_number);

CREATE UNIQUE INDEX "BusinessAccount_phonenumber_key" ON public."BusinessAccount" USING btree (phonenumber);

CREATE UNIQUE INDEX "BusinessAccount_pkey" ON public."BusinessAccount" USING btree (id);

CREATE UNIQUE INDEX "CountryVAT_country_key" ON public."CountryVAT" USING btree (country);

CREATE UNIQUE INDEX "CountryVAT_pkey" ON public."CountryVAT" USING btree (id);

alter table "public"."BusinessAccount" add constraint "BusinessAccount_pkey" PRIMARY KEY using index "BusinessAccount_pkey";

alter table "public"."CountryVAT" add constraint "CountryVAT_pkey" PRIMARY KEY using index "CountryVAT_pkey";

alter table "public"."BusinessAccount" add constraint "BusinessAccount_country_fkey" FOREIGN KEY (country) REFERENCES "CountryVAT"(country) ON UPDATE RESTRICT ON DELETE RESTRICT not valid;

alter table "public"."BusinessAccount" validate constraint "BusinessAccount_country_fkey";

alter table "public"."BusinessAccount" add constraint "BusinessAccount_email_key" UNIQUE using index "BusinessAccount_email_key";

alter table "public"."BusinessAccount" add constraint "BusinessAccount_org_number_key" UNIQUE using index "BusinessAccount_org_number_key";

alter table "public"."BusinessAccount" add constraint "BusinessAccount_phonenumber_key" UNIQUE using index "BusinessAccount_phonenumber_key";

alter table "public"."CountryVAT" add constraint "CountryVAT_country_key" UNIQUE using index "CountryVAT_country_key";

grant delete on table "public"."BusinessAccount" to "anon";

grant insert on table "public"."BusinessAccount" to "anon";

grant references on table "public"."BusinessAccount" to "anon";

grant select on table "public"."BusinessAccount" to "anon";

grant trigger on table "public"."BusinessAccount" to "anon";

grant truncate on table "public"."BusinessAccount" to "anon";

grant update on table "public"."BusinessAccount" to "anon";

grant delete on table "public"."BusinessAccount" to "authenticated";

grant insert on table "public"."BusinessAccount" to "authenticated";

grant references on table "public"."BusinessAccount" to "authenticated";

grant select on table "public"."BusinessAccount" to "authenticated";

grant trigger on table "public"."BusinessAccount" to "authenticated";

grant truncate on table "public"."BusinessAccount" to "authenticated";

grant update on table "public"."BusinessAccount" to "authenticated";

grant delete on table "public"."BusinessAccount" to "service_role";

grant insert on table "public"."BusinessAccount" to "service_role";

grant references on table "public"."BusinessAccount" to "service_role";

grant select on table "public"."BusinessAccount" to "service_role";

grant trigger on table "public"."BusinessAccount" to "service_role";

grant truncate on table "public"."BusinessAccount" to "service_role";

grant update on table "public"."BusinessAccount" to "service_role";

grant delete on table "public"."CountryVAT" to "anon";

grant insert on table "public"."CountryVAT" to "anon";

grant references on table "public"."CountryVAT" to "anon";

grant select on table "public"."CountryVAT" to "anon";

grant trigger on table "public"."CountryVAT" to "anon";

grant truncate on table "public"."CountryVAT" to "anon";

grant update on table "public"."CountryVAT" to "anon";

grant delete on table "public"."CountryVAT" to "authenticated";

grant insert on table "public"."CountryVAT" to "authenticated";

grant references on table "public"."CountryVAT" to "authenticated";

grant select on table "public"."CountryVAT" to "authenticated";

grant trigger on table "public"."CountryVAT" to "authenticated";

grant truncate on table "public"."CountryVAT" to "authenticated";

grant update on table "public"."CountryVAT" to "authenticated";

grant delete on table "public"."CountryVAT" to "service_role";

grant insert on table "public"."CountryVAT" to "service_role";

grant references on table "public"."CountryVAT" to "service_role";

grant select on table "public"."CountryVAT" to "service_role";

grant trigger on table "public"."CountryVAT" to "service_role";

grant truncate on table "public"."CountryVAT" to "service_role";

grant update on table "public"."CountryVAT" to "service_role";

create policy "Enable insert for anon users"
on "public"."BusinessAccount"
as permissive
for insert
to anon
with check (true);


create policy "Enable read access for all users"
on "public"."BusinessAccount"
as permissive
for select
to anon
using (true);


create policy "Enable insert for anon users"
on "public"."CountryVAT"
as permissive
for insert
to anon
with check (true);


create policy "Enable read access for all users"
on "public"."CountryVAT"
as permissive
for select
to anon
using (true);



