create table "public"."SupportedCountries" (
    "id" bigint generated by default as identity not null,
    "country" "SUPPORTED_COUNTRIES" not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."SupportedCountries" enable row level security;

create table "public"."SupportedLanguages" (
    "id" bigint generated by default as identity not null,
    "language" "SUPPORTED_LANGUAGES" not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."SupportedLanguages" enable row level security;

CREATE UNIQUE INDEX "SupportedCountries_country_key" ON public."SupportedCountries" USING btree (country);

CREATE UNIQUE INDEX "SupportedCountries_pkey" ON public."SupportedCountries" USING btree (id);

CREATE UNIQUE INDEX "SupportedLanguages_language_key" ON public."SupportedLanguages" USING btree (language);

CREATE UNIQUE INDEX "SupportedLanguages_pkey" ON public."SupportedLanguages" USING btree (id);

alter table "public"."SupportedCountries" add constraint "SupportedCountries_pkey" PRIMARY KEY using index "SupportedCountries_pkey";

alter table "public"."SupportedLanguages" add constraint "SupportedLanguages_pkey" PRIMARY KEY using index "SupportedLanguages_pkey";

alter table "public"."SupportedCountries" add constraint "SupportedCountries_country_key" UNIQUE using index "SupportedCountries_country_key";

alter table "public"."SupportedLanguages" add constraint "SupportedLanguages_language_key" UNIQUE using index "SupportedLanguages_language_key";

grant delete on table "public"."SupportedCountries" to "anon";

grant insert on table "public"."SupportedCountries" to "anon";

grant references on table "public"."SupportedCountries" to "anon";

grant select on table "public"."SupportedCountries" to "anon";

grant trigger on table "public"."SupportedCountries" to "anon";

grant truncate on table "public"."SupportedCountries" to "anon";

grant update on table "public"."SupportedCountries" to "anon";

grant delete on table "public"."SupportedCountries" to "authenticated";

grant insert on table "public"."SupportedCountries" to "authenticated";

grant references on table "public"."SupportedCountries" to "authenticated";

grant select on table "public"."SupportedCountries" to "authenticated";

grant trigger on table "public"."SupportedCountries" to "authenticated";

grant truncate on table "public"."SupportedCountries" to "authenticated";

grant update on table "public"."SupportedCountries" to "authenticated";

grant delete on table "public"."SupportedCountries" to "service_role";

grant insert on table "public"."SupportedCountries" to "service_role";

grant references on table "public"."SupportedCountries" to "service_role";

grant select on table "public"."SupportedCountries" to "service_role";

grant trigger on table "public"."SupportedCountries" to "service_role";

grant truncate on table "public"."SupportedCountries" to "service_role";

grant update on table "public"."SupportedCountries" to "service_role";

grant delete on table "public"."SupportedLanguages" to "anon";

grant insert on table "public"."SupportedLanguages" to "anon";

grant references on table "public"."SupportedLanguages" to "anon";

grant select on table "public"."SupportedLanguages" to "anon";

grant trigger on table "public"."SupportedLanguages" to "anon";

grant truncate on table "public"."SupportedLanguages" to "anon";

grant update on table "public"."SupportedLanguages" to "anon";

grant delete on table "public"."SupportedLanguages" to "authenticated";

grant insert on table "public"."SupportedLanguages" to "authenticated";

grant references on table "public"."SupportedLanguages" to "authenticated";

grant select on table "public"."SupportedLanguages" to "authenticated";

grant trigger on table "public"."SupportedLanguages" to "authenticated";

grant truncate on table "public"."SupportedLanguages" to "authenticated";

grant update on table "public"."SupportedLanguages" to "authenticated";

grant delete on table "public"."SupportedLanguages" to "service_role";

grant insert on table "public"."SupportedLanguages" to "service_role";

grant references on table "public"."SupportedLanguages" to "service_role";

grant select on table "public"."SupportedLanguages" to "service_role";

grant trigger on table "public"."SupportedLanguages" to "service_role";

grant truncate on table "public"."SupportedLanguages" to "service_role";

grant update on table "public"."SupportedLanguages" to "service_role";


